
#@echo hello

KERNEL_VERSION := 4.10.0-rc7+
STR1 := $(subst ., ,$(KERNEL_VERSION))
WORD1 := $(word 1, $(STR1))
WORD2 := $(word 2, $(STR1))


all:
	@echo hello
	@echo $(KERNEL_VERSION)
	@echo $(STR1)
	@echo $(WORD1)
	@echo $(WORD2)

